version: '3.8'
services:
  postgres:
    container_name: 'postgres-db'
    image: 'postgres:15'
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'data-postgres:/var/lib/postgresql/data'
    networks:
      - local
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

volumes:
  data-postgres:
    driver: local

networks:
  local:
    name: local-dev
    external: true
